export const ADD_OR_UPDATE_VIDEO = 'ADD_OR_UPDATE_VIDEO';
export const DELETE_VIDEO = 'DEL_VIDEO';
export const UPDATE_VIDEO_BY_INDEX = 'UPDATE_VIDEO_BY_INDEX';
export const ADD_OR_UPDATE_DOWNLOAD_INFO = 'ADD_OR_UPDATE_DOWNLOAD_INFO';
export const DELETE_DOWNLOAD_INFO = 'DELETE_DOWNLOAD_INFO';
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
