export const ADD_OR_UPDATE_VIDEO = 'ADD_OR_UPDATE_VIDEO';
export const DELETE_VIDEO = 'DEL_VIDEO';
export const ADD_OR_UPDATE_DOWNLOAD_INFO = 'ADD_OR_UPDATE_DOWNLOAD_INFO';
export const DELETE_DOWNLOAD_INFO = 'DELETE_DOWNLOAD_INFO';
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
export const RESET_VIDEO_INFO = 'RESET_VIDEO_INFO';
export const RESET_DOWNLOAD_INFO = 'RESET_DOWNLOAD_INFO';
export const UPDATE_LATEST_TAB = 'UPDATE_LATEST_TAB';
