export const DOWNLOAD_VIDEO_START = 'DOWNLOAD_VIDEO_START';

export const DOWNLOAD_VIDEO_FINISHED = 'DOWNLOAD_VIDEO_FINISHED';

export const DELETED_VIDEO = 'DELETE_VIDEO';

export const UPDATE_DOWNLOAD_PROGRESS = 'UPDATE_DOWNLOAD_PROGRESS';

export const ADD_NEW_VIDEO = 'ADD_NEW_VIDEO';

export const UNKNOWN_ACTION = 'UNKNOWN_ACTION';
